/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/agenda` | `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/guests` | `/guests`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/panel` | `/panel`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/scanner` | `/scanner`; params?: Router.UnknownInputParams; } | { pathname: `${'/(attendee)'}/agenda` | `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `${'/(attendee)'}/attendees` | `/attendees`; params?: Router.UnknownInputParams; } | { pathname: `${'/(attendee)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(attendee)'}/qr-pass` | `/qr-pass`; params?: Router.UnknownInputParams; } | { pathname: `${'/(attendee)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/agenda` | `/agenda`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/guests` | `/guests`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/panel` | `/panel`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/scanner` | `/scanner`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(attendee)'}/agenda` | `/agenda`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(attendee)'}/attendees` | `/attendees`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(attendee)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(attendee)'}/qr-pass` | `/qr-pass`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(attendee)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/agenda${`?${string}` | `#${string}` | ''}` | `/agenda${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/guests${`?${string}` | `#${string}` | ''}` | `/guests${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/panel${`?${string}` | `#${string}` | ''}` | `/panel${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/scanner${`?${string}` | `#${string}` | ''}` | `/scanner${`?${string}` | `#${string}` | ''}` | `${'/(attendee)'}/agenda${`?${string}` | `#${string}` | ''}` | `/agenda${`?${string}` | `#${string}` | ''}` | `${'/(attendee)'}/attendees${`?${string}` | `#${string}` | ''}` | `/attendees${`?${string}` | `#${string}` | ''}` | `${'/(attendee)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(attendee)'}/qr-pass${`?${string}` | `#${string}` | ''}` | `/qr-pass${`?${string}` | `#${string}` | ''}` | `${'/(attendee)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/agenda` | `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/guests` | `/guests`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/panel` | `/panel`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/scanner` | `/scanner`; params?: Router.UnknownInputParams; } | { pathname: `${'/(attendee)'}/agenda` | `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `${'/(attendee)'}/attendees` | `/attendees`; params?: Router.UnknownInputParams; } | { pathname: `${'/(attendee)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(attendee)'}/qr-pass` | `/qr-pass`; params?: Router.UnknownInputParams; } | { pathname: `${'/(attendee)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; };
    }
  }
}
